### ISSUE TITLE
GraphUnzip crashed

### ISSUE THREAD

**Issue by jflot** [nadegeguiglielmoni/GraphUnzip#12]
I tried running GraphUnzip on a SPAdes Illumina assembly of a ca. 250 Mb genome, after aligning 156 000 Nanopore reads > 10 kb in length on the GFA using SPAligner (command: `spaligner spaligner_config.yaml -d nanopore -s ONT_10kbmin.fastq -g SPADES_nanopore_assembly_graph_with_scaffolds.gfa -k 77 -t 14 -o spaligner`. Alignment went well, with > 99.9% of reads mapping on the graph. However, GraphUnzip crashed afterward (command: `graphunzip.py -g SPADES_assembly_graph_with_scaffolds.gfa -l spaligner/alignment.tsv -o SPADES_assembly_graph_with_scaffolds_GraphUnzip.gfa -f SPADES_assembly_graph_with_scaffolds_GraphUnzip.fasta unzip`). Here is the log:

Loading the GFA file
Loading contigs
Loading links
Everything loaded, moving on to untangling the graph
Reading the gpa file...
Finished going through the gpa file.
Inventoried  1000  long reads over  73428
Inventoried  2000  long reads over  73428
Inventoried  3000  long reads over  73428
Inventoried  4000  long reads over  73428
Inventoried  5000  long reads over  73428
Inventoried  6000  long reads over  73428
Inventoried  7000  long reads over  73428
Inventoried  8000  long reads over  73428
Inventoried  9000  long reads over  73428
Inventoried  10000  long reads over  73428
Inventoried  11000  long reads over  73428
Inventoried  12000  long reads over  73428
Inventoried  13000  long reads over  73428
Inventoried  14000  long reads over  73428
Inventoried  15000  long reads over  73428
Inventoried  16000  long reads over  73428
Inventoried  17000  long reads over  73428
Inventoried  18000  long reads over  73428
Inventoried  19000  long reads over  73428
Inventoried  20000  long reads over  73428
Inventoried  21000  long reads over  73428
Inventoried  22000  long reads over  73428
Inventoried  23000  long reads over  73428
Inventoried  24000  long reads over  73428
Inventoried  25000  long reads over  73428
Inventoried  26000  long reads over  73428
Inventoried  27000  long reads over  73428
Inventoried  28000  long reads over  73428
Inventoried  29000  long reads over  73428
Inventoried  30000  long reads over  73428
Inventoried  31000  long reads over  73428
Inventoried  32000  long reads over  73428
Inventoried  33000  long reads over  73428
Inventoried  34000  long reads over  73428
Inventoried  35000  long reads over  73428
Inventoried  36000  long reads over  73428
Inventoried  37000  long reads over  73428
Inventoried  38000  long reads over  73428
Inventoried  39000  long reads over  73428
Inventoried  40000  long reads over  73428
Inventoried  41000  long reads over  73428
Inventoried  42000  long reads over  73428
Inventoried  43000  long reads over  73428
Inventoried  44000  long reads over  73428
Inventoried  45000  long reads over  73428
Inventoried  46000  long reads over  73428
Inventoried  47000  long reads over  73428
Inventoried  48000  long reads over  73428
Inventoried  49000  long reads over  73428
Inventoried  50000  long reads over  73428
Inventoried  51000  long reads over  73428
Inventoried  52000  long reads over  73428
Inventoried  53000  long reads over  73428
Inventoried  54000  long reads over  73428
Inventoried  55000  long reads over  73428
Inventoried  56000  long reads over  73428
Inventoried  57000  long reads over  73428
Inventoried  58000  long reads over  73428
Inventoried  59000  long reads over  73428
Inventoried  60000  long reads over  73428
Inventoried  61000  long reads over  73428
Inventoried  62000  long reads over  73428
Inventoried  63000  long reads over  73428
Inventoried  64000  long reads over  73428
Inventoried  65000  long reads over  73428
Inventoried  66000  long reads over  73428
Inventoried  67000  long reads over  73428
Inventoried  68000  long reads over  73428
Inventoried  69000  long reads over  73428
Inventoried  70000  long reads over  73428
Inventoried  71000  long reads over  73428
Inventoried  72000  long reads over  73428
Inventoried  73000  long reads over  73428
Building consensus bridges from all the long reads
consensused  0  bridges out of  51462
consensused  100  bridges out of  51462
consensused  200  bridges out of  51462
consensused  300  bridges out of  51462
consensused  400  bridges out of  51462
consensused  500  bridges out of  51462
consensused  600  bridges out of  51462
consensused  700  bridges out of  51462
consensused  800  bridges out of  51462
consensused  900  bridges out of  51462
consensused  1000  bridges out of  51462
consensused  1100  bridges out of  51462
consensused  1200  bridges out of  51462
consensused  1300  bridges out of  51462
consensused  1400  bridges out of  51462
consensused  1500  bridges out of  51462
consensused  1600  bridges out of  51462
consensused  1700  bridges out of  51462
consensused  1800  bridges out of  51462
consensused  1900  bridges out of  51462
consensused  2000  bridges out of  51462
consensused  2100  bridges out of  51462
consensused  2200  bridges out of  51462
consensused  2300  bridges out of  51462
consensused  2400  bridges out of  51462
consensused  2500  bridges out of  51462
consensused  2600  bridges out of  51462
consensused  2700  bridges out of  51462
consensused  2800  bridges out of  51462
consensused  2900  bridges out of  51462
consensused  3000  bridges out of  51462
consensused  3100  bridges out of  51462
consensused  3200  bridges out of  51462
consensused  3300  bridges out of  51462
consensused  3400  bridges out of  51462
consensused  3500  bridges out of  51462
consensused  3600  bridges out of  51462
consensused  3700  bridges out of  51462
consensused  3800  bridges out of  51462
consensused  3900  bridges out of  51462
consensused  4000  bridges out of  51462
consensused  4100  bridges out of  51462
consensused  4200  bridges out of  51462
consensused  4300  bridges out of  51462
consensused  4400  bridges out of  51462
consensused  4500  bridges out of  51462
consensused  4600  bridges out of  51462
consensused  4700  bridges out of  51462
consensused  4800  bridges out of  51462
consensused  4900  bridges out of  51462
consensused  5000  bridges out of  51462
consensused  5100  bridges out of  51462
consensused  5200  bridges out of  51462
consensused  5300  bridges out of  51462
consensused  5400  bridges out of  51462
consensused  5500  bridges out of  51462
consensused  5600  bridges out of  51462
consensused  5700  bridges out of  51462
consensused  5800  bridges out of  51462
consensused  5900  bridges out of  51462
consensused  6000  bridges out of  51462
consensused  6100  bridges out of  51462
consensused  6200  bridges out of  51462
consensused  6300  bridges out of  51462
consensused  6400  bridges out of  51462
consensused  6500  bridges out of  51462
consensused  6600  bridges out of  51462
consensused  6700  bridges out of  51462
consensused  6800  bridges out of  51462
consensused  6900  bridges out of  51462
consensused  7000  bridges out of  51462
consensused  7100  bridges out of  51462
consensused  7200  bridges out of  51462
consensused  7300  bridges out of  51462
consensused  7400  bridges out of  51462
consensused  7500  bridges out of  51462
consensused  7600  bridges out of  51462
consensused  7700  bridges out of  51462
consensused  7800  bridges out of  51462
consensused  7900  bridges out of  51462
consensused  8000  bridges out of  51462
consensused  8100  bridges out of  51462
consensused  8200  bridges out of  51462
consensused  8300  bridges out of  51462
consensused  8400  bridges out of  51462
consensused  8500  bridges out of  51462
consensused  8600  bridges out of  51462
consensused  8700  bridges out of  51462
consensused  8800  bridges out of  51462
consensused  8900  bridges out of  51462
consensused  9000  bridges out of  51462
consensused  9100  bridges out of  51462
consensused  9200  bridges out of  51462
consensused  9300  bridges out of  51462
consensused  9400  bridges out of  51462
consensused  9500  bridges out of  51462
consensused  9600  bridges out of  51462
consensused  9700  bridges out of  51462
consensused  9800  bridges out of  51462
consensused  9900  bridges out of  51462
consensused  10000  bridges out of  51462
consensused  10100  bridges out of  51462
consensused  10200  bridges out of  51462
consensused  10300  bridges out of  51462
consensused  10400  bridges out of  51462
consensused  10500  bridges out of  51462
consensused  10600  bridges out of  51462
consensused  10700  bridges out of  51462
consensused  10800  bridges out of  51462
consensused  10900  bridges out of  51462
consensused  11000  bridges out of  51462
consensused  11100  bridges out of  51462
consensused  11200  bridges out of  51462
consensused  11300  bridges out of  51462
consensused  11400  bridges out of  51462
consensused  11500  bridges out of  51462
consensused  11600  bridges out of  51462
consensused  11700  bridges out of  51462
consensused  11800  bridges out of  51462
consensused  11900  bridges out of  51462
consensused  12000  bridges out of  51462
consensused  12100  bridges out of  51462
consensused  12200  bridges out of  51462
consensused  12300  bridges out of  51462
consensused  12400  bridges out of  51462
consensused  12500  bridges out of  51462
consensused  12600  bridges out of  51462
consensused  12700  bridges out of  51462
consensused  12800  bridges out of  51462
consensused  12900  bridges out of  51462
consensused  13000  bridges out of  51462
consensused  13100  bridges out of  51462
consensused  13200  bridges out of  51462
consensused  13300  bridges out of  51462
consensused  13400  bridges out of  51462
consensused  13500  bridges out of  51462
consensused  13600  bridges out of  51462
consensused  13700  bridges out of  51462
consensused  13800  bridges out of  51462
consensused  13900  bridges out of  51462
consensused  14000  bridges out of  51462
consensused  14100  bridges out of  51462
consensused  14200  bridges out of  51462
consensused  14300  bridges out of  51462
consensused  14400  bridges out of  51462
consensused  14500  bridges out of  51462
consensused  14600  bridges out of  51462
consensused  14700  bridges out of  51462
consensused  14800  bridges out of  51462
consensused  14900  bridges out of  51462
consensused  15000  bridges out of  51462
consensused  15100  bridges out of  51462
consensused  15200  bridges out of  51462
consensused  15300  bridges out of  51462
consensused  15400  bridges out of  51462
consensused  15500  bridges out of  51462
consensused  15600  bridges out of  51462
consensused  15700  bridges out of  51462
consensused  15800  bridges out of  51462
consensused  15900  bridges out of  51462
consensused  16000  bridges out of  51462
consensused  16100  bridges out of  51462
consensused  16200  bridges out of  51462
consensused  16300  bridges out of  51462
consensused  16400  bridges out of  51462
consensused  16500  bridges out of  51462
consensused  16600  bridges out of  51462
consensused  16700  bridges out of  51462
consensused  16800  bridges out of  51462
consensused  16900  bridges out of  51462
consensused  17000  bridges out of  51462
consensused  17100  bridges out of  51462
consensused  17200  bridges out of  51462
consensused  17300  bridges out of  51462
consensused  17400  bridges out of  51462
consensused  17500  bridges out of  51462
consensused  17600  bridges out of  51462
consensused  17700  bridges out of  51462
consensused  17800  bridges out of  51462
consensused  17900  bridges out of  51462
consensused  18000  bridges out of  51462
consensused  18100  bridges out of  51462
consensused  18200  bridges out of  51462
consensused  18300  bridges out of  51462
consensused  18400  bridges out of  51462
consensused  18500  bridges out of  51462
consensused  18600  bridges out of  51462
consensused  18700  bridges out of  51462
consensused  18800  bridges out of  51462
consensused  18900  bridges out of  51462
consensused  19000  bridges out of  51462
consensused  19100  bridges out of  51462
consensused  19200  bridges out of  51462
consensused  19300  bridges out of  51462
consensused  19400  bridges out of  51462
consensused  19500  bridges out of  51462
consensused  19600  bridges out of  51462
consensused  19700  bridges out of  51462
consensused  19800  bridges out of  51462
consensused  19900  bridges out of  51462
consensused  20000  bridges out of  51462
consensused  20100  bridges out of  51462
consensused  20200  bridges out of  51462
consensused  20300  bridges out of  51462
consensused  20400  bridges out of  51462
consensused  20500  bridges out of  51462
consensused  20600  bridges out of  51462
consensused  20700  bridges out of  51462
consensused  20800  bridges out of  51462
consensused  20900  bridges out of  51462
consensused  21000  bridges out of  51462
consensused  21100  bridges out of  51462
consensused  21200  bridges out of  51462
consensused  21300  bridges out of  51462
consensused  21400  bridges out of  51462
consensused  21500  bridges out of  51462
consensused  21600  bridges out of  51462
consensused  21700  bridges out of  51462
consensused  21800  bridges out of  51462
consensused  21900  bridges out of  51462
consensused  22000  bridges out of  51462
consensused  22100  bridges out of  51462
consensused  22200  bridges out of  51462
consensused  22300  bridges out of  51462
consensused  22400  bridges out of  51462
consensused  22500  bridges out of  51462
consensused  22600  bridges out of  51462
consensused  22700  bridges out of  51462
consensused  22800  bridges out of  51462
consensused  22900  bridges out of  51462
consensused  23000  bridges out of  51462
consensused  23100  bridges out of  51462
consensused  23200  bridges out of  51462
consensused  23300  bridges out of  51462
consensused  23400  bridges out of  51462
consensused  23500  bridges out of  51462
consensused  23600  bridges out of  51462
consensused  23700  bridges out of  51462
consensused  23800  bridges out of  51462
consensused  23900  bridges out of  51462
consensused  24000  bridges out of  51462
consensused  24100  bridges out of  51462
consensused  24200  bridges out of  51462
consensused  24300  bridges out of  51462
consensused  24400  bridges out of  51462
consensused  24500  bridges out of  51462
consensused  24600  bridges out of  51462
consensused  24700  bridges out of  51462
consensused  24800  bridges out of  51462
consensused  24900  bridges out of  51462
consensused  25000  bridges out of  51462
consensused  25100  bridges out of  51462
consensused  25200  bridges out of  51462
consensused  25300  bridges out of  51462
consensused  25400  bridges out of  51462
consensused  25500  bridges out of  51462
consensused  25600  bridges out of  51462
consensused  25700  bridges out of  51462
consensused  25800  bridges out of  51462
consensused  25900  bridges out of  51462
consensused  26000  bridges out of  51462
consensused  26100  bridges out of  51462
consensused  26200  bridges out of  51462
consensused  26300  bridges out of  51462
consensused  26400  bridges out of  51462
consensused  26500  bridges out of  51462
consensused  26600  bridges out of  51462
consensused  26700  bridges out of  51462
consensused  26800  bridges out of  51462
consensused  26900  bridges out of  51462
consensused  27000  bridges out of  51462
consensused  27100  bridges out of  51462
consensused  27200  bridges out of  51462
consensused  27300  bridges out of  51462
consensused  27400  bridges out of  51462
consensused  27500  bridges out of  51462
consensused  27600  bridges out of  51462
consensused  27700  bridges out of  51462
consensused  27800  bridges out of  51462
consensused  27900  bridges out of  51462
consensused  28000  bridges out of  51462
consensused  28100  bridges out of  51462
consensused  28200  bridges out of  51462
consensused  28300  bridges out of  51462
consensused  28400  bridges out of  51462
consensused  28500  bridges out of  51462
consensused  28600  bridges out of  51462
consensused  28700  bridges out of  51462
consensused  28800  bridges out of  51462
consensused  28900  bridges out of  51462
consensused  29000  bridges out of  51462
consensused  29100  bridges out of  51462
consensused  29200  bridges out of  51462
consensused  29300  bridges out of  51462
consensused  29400  bridges out of  51462
consensused  29500  bridges out of  51462
consensused  29600  bridges out of  51462
consensused  29700  bridges out of  51462
consensused  29800  bridges out of  51462
consensused  29900  bridges out of  51462
consensused  30000  bridges out of  51462
consensused  30100  bridges out of  51462
consensused  30200  bridges out of  51462
consensused  30300  bridges out of  51462
consensused  30400  bridges out of  51462
consensused  30500  bridges out of  51462
consensused  30600  bridges out of  51462
consensused  30700  bridges out of  51462
consensused  30800  bridges out of  51462
consensused  30900  bridges out of  51462
consensused  31000  bridges out of  51462
consensused  31100  bridges out of  51462
consensused  31200  bridges out of  51462
consensused  31300  bridges out of  51462
consensused  31400  bridges out of  51462
consensused  31500  bridges out of  51462
consensused  31600  bridges out of  51462
consensused  31700  bridges out of  51462
consensused  31800  bridges out of  51462
consensused  31900  bridges out of  51462
consensused  32000  bridges out of  51462
consensused  32100  bridges out of  51462
consensused  32200  bridges out of  51462
consensused  32300  bridges out of  51462
consensused  32400  bridges out of  51462
consensused  32500  bridges out of  51462
consensused  32600  bridges out of  51462
consensused  32700  bridges out of  51462
consensused  32800  bridges out of  51462
consensused  32900  bridges out of  51462
consensused  33000  bridges out of  51462
consensused  33100  bridges out of  51462
consensused  33200  bridges out of  51462
consensused  33300  bridges out of  51462
consensused  33400  bridges out of  51462
consensused  33500  bridges out of  51462
consensused  33600  bridges out of  51462
consensused  33700  bridges out of  51462
consensused  33800  bridges out of  51462
consensused  33900  bridges out of  51462
consensused  34000  bridges out of  51462
consensused  34100  bridges out of  51462
consensused  34200  bridges out of  51462
consensused  34300  bridges out of  51462
consensused  34400  bridges out of  51462
consensused  34500  bridges out of  51462
consensused  34600  bridges out of  51462
consensused  34700  bridges out of  51462
consensused  34800  bridges out of  51462
consensused  34900  bridges out of  51462
consensused  35000  bridges out of  51462
consensused  35100  bridges out of  51462
consensused  35200  bridges out of  51462
consensused  35300  bridges out of  51462
consensused  35400  bridges out of  51462
consensused  35500  bridges out of  51462
consensused  35600  bridges out of  51462
consensused  35700  bridges out of  51462
consensused  35800  bridges out of  51462
consensused  35900  bridges out of  51462
consensused  36000  bridges out of  51462
consensused  36100  bridges out of  51462
consensused  36200  bridges out of  51462
consensused  36300  bridges out of  51462
consensused  36400  bridges out of  51462
consensused  36500  bridges out of  51462
consensused  36600  bridges out of  51462
consensused  36700  bridges out of  51462
consensused  36800  bridges out of  51462
consensused  36900  bridges out of  51462
consensused  37000  bridges out of  51462
consensused  37100  bridges out of  51462
consensused  37200  bridges out of  51462
consensused  37300  bridges out of  51462
consensused  37400  bridges out of  51462
consensused  37500  bridges out of  51462
consensused  37600  bridges out of  51462
consensused  37700  bridges out of  51462
consensused  37800  bridges out of  51462
consensused  37900  bridges out of  51462
consensused  38000  bridges out of  51462
consensused  38100  bridges out of  51462
consensused  38200  bridges out of  51462
consensused  38300  bridges out of  51462
consensused  38400  bridges out of  51462
consensused  38500  bridges out of  51462
consensused  38600  bridges out of  51462
consensused  38700  bridges out of  51462
consensused  38800  bridges out of  51462
consensused  38900  bridges out of  51462
consensused  39000  bridges out of  51462
consensused  39100  bridges out of  51462
consensused  39200  bridges out of  51462
consensused  39300  bridges out of  51462
consensused  39400  bridges out of  51462
consensused  39500  bridges out of  51462
consensused  39600  bridges out of  51462
consensused  39700  bridges out of  51462
consensused  39800  bridges out of  51462
consensused  39900  bridges out of  51462
consensused  40000  bridges out of  51462
consensused  40100  bridges out of  51462
consensused  40200  bridges out of  51462
consensused  40300  bridges out of  51462
consensused  40400  bridges out of  51462
consensused  40500  bridges out of  51462
consensused  40600  bridges out of  51462
consensused  40700  bridges out of  51462
consensused  40800  bridges out of  51462
consensused  40900  bridges out of  51462
consensused  41000  bridges out of  51462
consensused  41100  bridges out of  51462
consensused  41200  bridges out of  51462
consensused  41300  bridges out of  51462
consensused  41400  bridges out of  51462
consensused  41500  bridges out of  51462
consensused  41600  bridges out of  51462
consensused  41700  bridges out of  51462
consensused  41800  bridges out of  51462
consensused  41900  bridges out of  51462
consensused  42000  bridges out of  51462
consensused  42100  bridges out of  51462
consensused  42200  bridges out of  51462
consensused  42300  bridges out of  51462
consensused  42400  bridges out of  51462
consensused  42500  bridges out of  51462
consensused  42600  bridges out of  51462
consensused  42700  bridges out of  51462
consensused  42800  bridges out of  51462
consensused  42900  bridges out of  51462
consensused  43000  bridges out of  51462
consensused  43100  bridges out of  51462
consensused  43200  bridges out of  51462
consensused  43300  bridges out of  51462
consensused  43400  bridges out of  51462
consensused  43500  bridges out of  51462
consensused  43600  bridges out of  51462
consensused  43700  bridges out of  51462
consensused  43800  bridges out of  51462
consensused  43900  bridges out of  51462
consensused  44000  bridges out of  51462
consensused  44100  bridges out of  51462
consensused  44200  bridges out of  51462
consensused  44300  bridges out of  51462
consensused  44400  bridges out of  51462
consensused  44500  bridges out of  51462
consensused  44600  bridges out of  51462
consensused  44700  bridges out of  51462
consensused  44800  bridges out of  51462
consensused  44900  bridges out of  51462
consensused  45000  bridges out of  51462
consensused  45100  bridges out of  51462
consensused  45200  bridges out of  51462
consensused  45300  bridges out of  51462
consensused  45400  bridges out of  51462
consensused  45500  bridges out of  51462
consensused  45600  bridges out of  51462
consensused  45700  bridges out of  51462
consensused  45800  bridges out of  51462
consensused  45900  bridges out of  51462
consensused  46000  bridges out of  51462
consensused  46100  bridges out of  51462
consensused  46200  bridges out of  51462
consensused  46300  bridges out of  51462
consensused  46400  bridges out of  51462
consensused  46500  bridges out of  51462
consensused  46600  bridges out of  51462
consensused  46700  bridges out of  51462
consensused  46800  bridges out of  51462
consensused  46900  bridges out of  51462
consensused  47000  bridges out of  51462
consensused  47100  bridges out of  51462
consensused  47200  bridges out of  51462
consensused  47300  bridges out of  51462
consensused  47400  bridges out of  51462
consensused  47500  bridges out of  51462
consensused  47600  bridges out of  51462
consensused  47700  bridges out of  51462
consensused  47800  bridges out of  51462
consensused  47900  bridges out of  51462
consensused  48000  bridges out of  51462
consensused  48100  bridges out of  51462
consensused  48200  bridges out of  51462
consensused  48300  bridges out of  51462
consensused  48400  bridges out of  51462
consensused  48500  bridges out of  51462
consensused  48600  bridges out of  51462
consensused  48700  bridges out of  51462
consensused  48800  bridges out of  51462
consensused  48900  bridges out of  51462
consensused  49000  bridges out of  51462
consensused  49100  bridges out of  51462
consensused  49200  bridges out of  51462
consensused  49300  bridges out of  51462
consensused  49400  bridges out of  51462
consensused  49500  bridges out of  51462
consensused  49600  bridges out of  51462
consensused  49700  bridges out of  51462
consensused  49800  bridges out of  51462
consensused  49900  bridges out of  51462
consensused  50000  bridges out of  51462
consensused  50100  bridges out of  51462
consensused  50200  bridges out of  51462
consensused  50300  bridges out of  51462
consensused  50400  bridges out of  51462
consensused  50500  bridges out of  51462
consensused  50600  bridges out of  51462
consensused  50700  bridges out of  51462
consensused  50800  bridges out of  51462
consensused  50900  bridges out of  51462
consensused  51000  bridges out of  51462
consensused  51100  bridges out of  51462
consensused  51200  bridges out of  51462
consensused  51300  bridges out of  51462
consensused  51400  bridges out of  51462
Done building consensus bridges
Now we will determine through an iterative process what contigs of the assembly are present only once in the final genome
Out of  51462  supposed single-copy contigs,  11975  were not actually haploid. Recomputing until all the single-copy contigs are robust.
Out of  39487  supposed single-copy contigs,  4719  were not actually haploid. Recomputing until all the single-copy contigs are robust.
Out of  34768  supposed single-copy contigs,  2333  were not actually haploid. Recomputing until all the single-copy contigs are robust.
Out of  32435  supposed single-copy contigs,  1244  were not actually haploid. Recomputing until all the single-copy contigs are robust.
Out of  31191  supposed single-copy contigs,  744  were not actually haploid. Recomputing until all the single-copy contigs are robust.
Out of  30447  supposed single-copy contigs,  412  were not actually haploid. Recomputing until all the single-copy contigs are robust.
Out of  30035  supposed single-copy contigs,  253  were not actually haploid. Recomputing until all the single-copy contigs are robust.
Out of  29782  supposed single-copy contigs,  148  were not actually haploid. Recomputing until all the single-copy contigs are robust.
Out of  29634  supposed single-copy contigs,  92  were not actually haploid. Recomputing until all the single-copy contigs are robust.
Out of  29542  supposed single-copy contigs,  59  were not actually haploid. Recomputing until all the single-copy contigs are robust.
Out of  29483  supposed single-copy contigs,  37  were not actually haploid. Recomputing until all the single-copy contigs are robust.
Out of  29446  supposed single-copy contigs,  30  were not actually haploid. Recomputing until all the single-copy contigs are robust.
Out of  29416  supposed single-copy contigs,  21  were not actually haploid. Recomputing until all the single-copy contigs are robust.
Out of  29395  supposed single-copy contigs,  13  were not actually haploid. Recomputing until all the single-copy contigs are robust.
Out of  29382  supposed single-copy contigs,  8  were not actually haploid. Recomputing until all the single-copy contigs are robust.
Out of  29374  supposed single-copy contigs,  6  were not actually haploid. Recomputing until all the single-copy contigs are robust.
Out of  29368  supposed single-copy contigs,  4  were not actually haploid. Recomputing until all the single-copy contigs are robust.
Out of  29364  supposed single-copy contigs,  3  were not actually haploid. Recomputing until all the single-copy contigs are robust.
Out of  29361  supposed single-copy contigs,  3  were not actually haploid. Recomputing until all the single-copy contigs are robust.
Out of  29358  supposed single-copy contigs,  3  were not actually haploid. Recomputing until all the single-copy contigs are robust.
Out of  29355  supposed single-copy contigs,  1  were not actually haploid. Recomputing until all the single-copy contigs are robust.
Let's move on to actually untangling the graph
Processed  0  contigs out of  102461 , while untangling with long reads
Processed  1000  contigs out of  102461 , while untangling with long reads
Processed  2000  contigs out of  102461 , while untangling with long reads
Processed  3000  contigs out of  102461 , while untangling with long reads
Processed  4000  contigs out of  102461 , while untangling with long reads
Debug WARNING,  ['271376', '16521597', '272120', '77390718', '7591698']  : looking for  ['7591698']   0  from  ['77390718']  among  [['7591698'], ['14360169']]   [1, 1]   271376   <16521597>272120<77390718>7591698
Processed  5000  contigs out of  102461 , while untangling with long reads
Processed  6000  contigs out of  102461 , while untangling with long reads
Processed  7000  contigs out of  102461 , while untangling with long reads
Processed  8000  contigs out of  102461 , while untangling with long reads
Processed  9000  contigs out of  102461 , while untangling with long reads
Processed  10000  contigs out of  102461 , while untangling with long reads
Processed  11000  contigs out of  102461 , while untangling with long reads
Processed  12000  contigs out of  102461 , while untangling with long reads
Processed  13000  contigs out of  102461 , while untangling with long reads
Processed  14000  contigs out of  102461 , while untangling with long reads
Processed  15000  contigs out of  102461 , while untangling with long reads
Debug WARNING,  ['4229900', '16324833', '16324841', '16324849', '16324859', '16324867', '16324873', '16324879', '16324885', '16324897', '16324903', '16472453', '16445741', '16445753', '16445759', '16445765', '16538773', '16538779', '16538787', '16538797', '16538803', '16538809', '81112111', '16538809', '53260245', '82122851', '6222572', '4773173']  : looking for  ['81112111']   0  from  ['16538809']  among  [['81112111'], ['16538817']]   [1, 0]   4229900   >16324833>16324841>16324849>16324859>16324867>16324873>16324879>16324885>16324897>16324903>16472453>16445741>16445753>16445759>16445765>16538773>16538779>16538787>16538797>16538803>16538809>81112111<16538809<53260245<82122851<6222572>4773173
Processed  16000  contigs out of  102461 , while untangling with long reads
Processed  17000  contigs out of  102461 , while untangling with long reads
Processed  18000  contigs out of  102461 , while untangling with long reads
Processed  19000  contigs out of  102461 , while untangling with long reads
Processed  20000  contigs out of  102461 , while untangling with long reads
Processed  21000  contigs out of  102461 , while untangling with long reads
Processed  22000  contigs out of  102461 , while untangling with long reads
Processed  23000  contigs out of  102461 , while untangling with long reads
Processed  24000  contigs out of  102461 , while untangling with long reads
Processed  25000  contigs out of  102461 , while untangling with long reads
Processed  26000  contigs out of  102461 , while untangling with long reads
Traceback (most recent call last):
  File "/Users/jff/.local/bin/graphunzip.py", line 335, in <module>
    main()
  File "/Users/jff/.local/bin/graphunzip.py", line 312, in main
    bridge_with_long_reads(segments, names, cn, lrFile, supported_links2, refHaploidy, multiplicities)
  File "/Users/jff/.local/src/GraphUnzip/solve_with_long_reads.py", line 120, in bridge_with_long_reads
    unzip_graph_with_bridges(segments, non_overlapping_bridges, copiesnumber, haploidContigs, haploidContigsNames, names, supported_links2, minimum_supported_links, multiplicities, longContigs)
  File "/Users/jff/.local/src/GraphUnzip/solve_with_long_reads.py", line 436, in unzip_graph_with_bridges
    CIGAR = segments[names[contigs[0]]].CIGARs[end][segment.find_this_link(segments[oldContigsIndices[1]], nextEnd, segments[names[contigs[0]]].links[end], segments[names[contigs[0]]].otherEndOfLinks[end])]
IndexError: list index out of range

**Comment by jflot** [comment]
I solved this problem by adding 
`import sys`
`sys.setrecursionlimit(10000)`
at the beginning of graphunzip.py

**Comment by RolandFaure** [comment]
Hi Jean-François,
I found the origin of the problem: it was that SPAligner does not always output alignments compatible with the assembly graph. I added a check in GraphUnzip so that alignments incompatible with the graph are discarded with a warning message. 
You can now use the new version, thank you for bringing up this problem
