### ISSUE TITLE
Error message when opening GFA in Bandage

### ISSUE THREAD

**Issue by jflot** [nadegeguiglielmoni/GraphUnzip#13]
<img width="426" alt="image" src="https://user-images.githubusercontent.com/19376319/146809054-dcc80fe9-003e-4a6f-9968-8430157bcbd8.png">

The GFA produced by GraphUnzip contains 81971 '77M' CIGARs and 37 '*', which is probably the source of the problem. In the pre-GraphUnzip GFA (produced by SPAdes), all overlaps were 77 bp, hence all overlaps should also be 77 bp in the post-GraphUnzip GFA.

**Comment by RolandFaure** [comment]
This warning message can happen if you had '*' as CIGAR strings in your original GFA. In this case, juste ignore the warning.
Since this is not the case here, this indicates a bug in GraphUnzip, the same one you highlighted in issue #12 . Working on it.

**Comment by RolandFaure** [comment]
The problem has been solved in the version I just pushed, thank you for bringing the problem up
