### ISSUE TITLE
Plans for Omni-C data?

### ISSUE THREAD

**Issue by talioto** [nadegeguiglielmoni/GraphUnzip#18]
Hi Nadège and Jean-François,

Are there any plans to support Omni-C? As it stands, GraphUnzip expects a fragment list, which of course would be ridiculous for Omni-C. I'd like to try GraphUnzip on Flye GFA output, but we only use Omni-C in-house. Of course I could just use the ONT reads again, but I'd like to try the Hi-C interaction matrix option.

-Tyler

**Comment by nadegeguiglielmoni** [comment]
Hello,

You can already use Omni-C data. When processing the reads with hicstuff,  use a value for -e, something around 100-1000 bp. Then your fragments will just be arbitrary fragments of this size.
