### ISSUE TITLE
How does GraphUnzip determine contig coverage?

### ISSUE THREAD

**Issue by Adamtaranto** [nadegeguiglielmoni/GraphUnzip#21]
Does GraphUnzip pull coverage info directly from the gfa tags (i.e. "DP")? Or is it calculated it from the mapped Hi-C  / long reads?

**Comment by RolandFaure** [comment]
Hello,

The coverage information is pulled from the "DP" tags.

**Comment by Adamtaranto** [comment]
I've got some Unicycler assemblies where the depth seems to be scaled to the homozygous coverage peak from the kmer spectra i.e. single copy region = 1.0x; collapsed 2-copy repeat = 2.0x; etc.

Will this work with GraphUnzip? or does it expect absolute depth (ie. median read depth per contig).

**Comment by RolandFaure** [comment]
Interesting question. GraphUnzip was first developed to work with absolute coverages, but I took a quick look in the code and it seems to me that it should work absolutely fine with relative coverage.

**Comment by Adamtaranto** [comment]
Do you know of any tools that will add depth tags to a GFA? I've got some miniasm assemblies that don't have depth info that I want to run through GraphUnzip.

**Comment by RolandFaure** [comment]
I do not know of such a tool so I quickly wrote a very basic one: [github.com/rolandfaure/compute_coverage](https://github.com/RolandFaure/compute_coverage). Basically it just maps reads to an assembly and deduces the coverage of every contig (wrt the reads provided).

**Comment by Adamtaranto** [comment]
Cool, thanks for that! 

I was thinking of using MosDepth to calc median coverage and then scrape the per contig values from the summary file. MosDepth does a nice job of handling all the weirdness with secondary alignments.

I don't have a good solution right now for calculating the total unique reads or total unique fragments (i.e. not double counting paired reads) for the RC and FC tags. 

I'll look into it and open a PR if I find something.

**Comment by RolandFaure** [comment]
The tool I wrote just uses --secondary=no in minimap2 and thus completely discards the secondary alignments. My feeling is that this is completely fine when using long reads, but may create weird artifacts when using short reads. 

To complete my first answer, note that GraphUnzip does not need a perfect coverage of all contigs: it estimates the multiplicity of each contig based on the absolute coverage but also the graph topology. Hence it might not be a problem if the coverage of a few contig is approximate.

**Comment by Adamtaranto** [comment]
I've forked your compute_coverage repo here: [GraphTagger](https://github.com/adamtaranto/Graphtagger) and added a few extra tools. 

`csv2tag` can be used to add custom tags from any source to a gfa file.
