### ISSUE TITLE
assembly with nanopore sequences

### ISSUE THREAD

**Issue by tothuhien** [nadegeguiglielmoni/GraphUnzip#23]
Hi, we only have nanopore sequences and used Flye to assemble them. I'm wondering if it's useful to use the nanopore sequences themselves to map to the graph produced by Flye, and use it to unzip the graph? 
Thanks in advance for your response! 
Hien

**Comment by RolandFaure** [comment]
EDIT after discussion with @nadegeguiglielmoni 

Hi,
I tested this on a dataset and it did not change at all the Flye assembly. But @nadegeguiglielmoni  brings to my attention that Flye sometimes collapses heterozygous regions when heterozygosity is low, in which case GraphUnzip could be of use to you (I havent tested in this case).

Thus there is no way to know but to test!

Roland

**Comment by tothuhien** [comment]
Thank you very much for the response, that's very helpful. 
I have other questions about how to run it. I see that Flye gives several gfa files: 
assembly_graph.gfa
30-contigger/graph_final.gfa
40-polishing/polished_edges.gfa

Which ones should I use for unzip? And after unzip the graph, how can I generate the new assembly contigs file?
Maybe I overlook but it seems that GraphUnzip only unzip the graph and do not generate the new assembly?
Looking forward for your response. 
Thanks,
Hien

**Comment by RolandFaure** [comment]
You should use the final Flye assembly, which should be directly in the output folder and named `assembly_graph.gfa`. GraphUnzip will produce a new gfa (and optionally fasta) assembly, indicated by the -o option (e.g. `-o unzipped_graph.gfa`)

**Comment by tothuhien** [comment]
Thanks. But I'm still a bit confused with the output.
For example, Flye gives me a graph with 74 nodes, 101 links, and 49 paths which corresponds to 49 contigs
While GraphUnzip gives me a graph of 72 nodes, 57 links, and no path. So is each node already a (super)contig that there's no need to have paths to define contigs? If so, why do we need links in this case. If not, do we need another step to generate contigs by linking nodes with paths as Flye has? Furthermore, the corresponding fasta file of GraphUnZip contains 72 contigs, which corresponds exactly to 72 nodes in the graph.
I don't know much about assembly graph, so my question may be confusing too :)
Thanks.

**Comment by RolandFaure** [comment]
This is indeed confusing, as Flye and GraphUnzip do not use Nodes, Paths and Contigs exactly in the same way.
GraphUnzip does not output any Paths because they would all be trivial (e.g. only one node) by design of GraphUnzip. Contigs are thus equivalent to the nodes of the GFA in the GraphUnzip output (which is not true for the Flye output)

**Comment by tothuhien** [comment]
ok I see, thanks for explanation. But if each path is one node in the GFA graph, so why do we still have links in the graph,  what do they use for?
For example in the output graph, I have :
```
S       supercontig_0 .....
S       supercontig_1 .....
S       supercontig_2 .....
S       supercontig_3 .....
S       supercontig_4 .....
S       supercontig_5 .....
S       supercontig_6 .....
 .....
L	supercontig_4	-	supercontig_23	-	0M
L	supercontig_5	-	supercontig_35	-	0M
L	supercontig_6	-	supercontig_58	-	0M
L	supercontig_6	+	supercontig_43	-	0M
```

**Comment by RolandFaure** [comment]
GraphUnzip outputs graphs where a contig (let's call it `a`) is typically linked with two homologous contigs at each end (`b` and `b'`). In this case, out of the two homologous contigs, one actually is next to `a` on the DNA strand, and the other on an homologous chromosome. GraphUnzip could not decide if the real genome contained `a-b` or `a-b'` and outputted both links . In other words, all the links in the final GFA do not represent links that are actually present in a genome. That is why they cannot be converted into contigs.
On the other hand, links can still be quite useful to locate the contig `a`: you know it is next to either contig `b` or `b'`, which is quite a rich information

**Comment by tothuhien** [comment]
I see, it's clear now. Thank you very much for your help, much appreciated!
