### ISSUE TITLE
the gfa results can‘t loaded in Bandage.

### ISSUE THREAD

**Issue by Yujiaxin419** [nadegeguiglielmoni/GraphUnzip#4]
Hi :

I ran GraphUnzip pipeline in a heterozygous genome with command line below:

```
## hifiASM ##
hifiasm -o prefix -l 0 -t 32 hifi.longreads.fq

## hicstuff ##
gfatools gfa2fa prefix_hifiasm.p_utg.gfa > prefix_hifiasm.p_utg.fasta
hicstuff pipeline --aligner bowtie2 --enzyme MboI --iterative -t 36 -g prefix_hifiasm.p_utg.fasta -o hic_out HiC.R1.fq.gz HiC.R2.fq.gz

## GraphAligner ##
GraphAligner -g prefix_hifiasm.p_utg.gfa -f hifi.longreads.fq -a aln.gaf -t 36 -x vg

## GraphUnzip ##
graph=prefix_hifiasm.p_utg.gfa
matrix=abs_fragments_contacts_weighted.txt
aln_gaf=aln.gaf
fragment=fragments_list.txt

python ~/software/GraphUnzip/main.py -g $graph -m $matrix -F $fragment -lr $aln_gaf --accept 0.40 --reject 0.10 --exhaustive --whole_match --minimum_match 0.8
```
This pipeline finally generated a 6.2GB assembly and its N50 is 383kb.

But this result graph cant be loaded in Bandage.

This is some line in this graph:
![image](https://user-images.githubusercontent.com/52374093/108938869-c7d3a480-768b-11eb-9a37-9e85efa3254d.png)
![image](https://user-images.githubusercontent.com/52374093/108939152-3c0e4800-768c-11eb-95b4-362d8ce4e3a1.png)

could you please give me some advise to solve this problem? Thanks a log.

Yu jiaxin

**Comment by nadegeguiglielmoni** [comment]
Hello,

Why can't you load it in Bandage? Do you get an error?

**Comment by Yujiaxin419** [comment]
Hi :

I got an error below when I load the graph in Bandage (v0.8.1 for windows)

![image](https://user-images.githubusercontent.com/52374093/108990471-de9cea00-76d1-11eb-982a-ff1bfb16a561.png)

**Comment by jflot** [comment]
I see that you are opening using the Windows version of Bandage a GFA file that was produced in Linux. This may be the cause of the problem, as a GFA is a text file and newline characters are different in Linux vs Windows (see https://en.wikipedia.org/wiki/Newline). Could you try to install the Linux version of Bandage and open your GFA within Linux to see whether this solves your problem?

**Comment by jflot** [comment]
You could also use unix2dos to convert the newline characters (https://en.wikipedia.org/wiki/Unix2dos).

**Comment by Yujiaxin419** [comment]
I had  follow your suggestion to convert the newline characters. But its useless. I think that this problem may caused by out of memory of my laptop.  My graph is too large to load in Bandage. 

Anyway, Thanks for giving the kind suggestion.
