### ISSUE TITLE
input

### ISSUE THREAD

**Issue by zhenzhenyang-psu** [nadegeguiglielmoni/GraphUnzip#6]
Hello there,
I read the GraphUnzip paper and think it is cool!
Regarding the input, are the matrix file (eg. abs_fragments_contacts_weighted.txt) and fragment file (fragments_list.txt) from hicstuff? Could you tell more information about the file format? Is it compatible with a matrix file generated from other tools?

For the file for the "-lr" argument, does it derive from mapping of long reads to the p_utg.gfa? In the case where long nanopore reads are unavailable, what is the point of using mapping result of hifi reads to the assembly graph? How does this differ from the file following "-g" argument (e.g. p_utg.gfa)?

Also, I wonder if GraphUnzip has a script to generate a fasta file from the phased assembly graph.
thanks,
zhenzhen

**Comment by zhenzhenyang-psu** [comment]
Sorry, what I really meant was how to generate a phased contig.gfa from a unitig.gfa

**Comment by nadegeguiglielmoni** [comment]
Hello,

We are glad that you appreciate GraphUnzip. 

The files abs_fragments_contacts_weighted.txt and fragments_list.txt are indeed from hicstuff. However, if you wish to use another pipeline, you can reconstitute these files. 

fragments_list.txt gives a list of all restriction fragments with an id, the corresponding chromosome, start position, end position, size and gc content:
```
id	chrom	start_pos	end_pos	size	gc_content
1	seq1	0	21	21	0.5238095238095238
2	seq1	21	80	59	0.576271186440678
3	seq1	80	328	248	0.5201612903225806
```
GraphUnzip does not use gc_content so you do not need to put actual values there. 

abs_fragments_contacts_weighted.txt is a sparse matrix that starts with a header containing the number of rows, number of columns and number of nonzero entries in the matrix. The next lines give the ids of two restriction fragments and the number of contacts between these fragments, when the number of contacts is not 0:
```
564	564	6978
0	0	3
1	2	4
1	3	3
```

The -lr argument is indeed for the mapping file of long reads, a GAF file obtained with GraphAligner. We have tested running GraphUnzip on HiFi assemblies using only HiFi reads and it could improve phasing and continuity a bit. 

There is not yet a script to get the contig.gfa, so far we have been using Bandage and the option "Merge all possible nodes". We recommend to check the output with Bandage anyway.

**Comment by zhenzhenyang-psu** [comment]
Thanks for such detailed reply! It is really helpful! 
Are the hifi reads mapped via GraphAligner longer than 15kbp?
thanks,
zhenzhen

**Comment by RolandFaure** [comment]
Hi,

You can map reads of any length via GraphAligner. However, the longest the read the more information you will be able to retrieve for it, the most interesting reads being those bridging several contigs.

**Comment by RolandFaure** [comment]
I'm going to update the answers to this question, as it may be helpful to others and GraphUnzip evolved since this issue was opened:
- for the input matrix file, Nadege's answer above is still perfectly relevant
- the '-l' (ex '-lr') argument indeed derives from the mapping of long reads to the .gfa
- if long nanopore reads were unavailable, you are very right to underline that mapping the same HiFi reads as those used in the assembly probably won't give you any extra information (except perhaps if you're using a DBG assembler, but that is not common)
- Now graphunzip has an option -f to generate a fasta file from the phased assembly
